#!/bin/bash
# File_Rel_Path: 'filesystemRoot/home/user/bashrc'
# File_Type: '.sh'
# Squash_Source: 'c3c94ba38425135a53c45b7512332b37321a8eda'

# [Previous content unchanged...]

if [ "$color_prompt" = yes ]; then
    # Timestamp in grey, non-bold
    PS1="\[\033[90m\]\$(date '+%m/%d/%y %H:%M:%S %Z (UTC%:z)')\[\033[00m\] ${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@$HOST_ALIAS$(git_prompt_info)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
else
    PS1="\$(date '+%m/%d/%y %H:%M:%S %Z (UTC%:z)') ${debian_chroot:+($debian_chroot)}\u@$HOST_ALIAS$(git_prompt_info):\w\$ "
fi

# [Remaining content unchanged...]
